import type { PersonalAgentState, WorldSlice } from '@/domain/world'
import { createAnthropicClient, getModel, streamText } from './anthropic'
import { extractWorldKnowledge } from '@/engine/world-knowledge'

/**
 * LLM Agent decision result - fully LLM-driven, no fixed action types
 */
export type SystemFeedback = {
  reputation_impact?: { dimension: string; delta: number; reason: string }[]
  current_role?: string
  role_conflict?: string
  resource_action?: { resource: string; strategy: 'direct_compete' | 'cooperate' | 'share' | 'hoard' | 'steal' | 'deceive'; amount_hint: number }
  tension_effect?: 'building' | 'releasing' | 'neutral'
  meme_spread?: { content: string; category: 'belief' | 'behavior' | 'knowledge' | 'emotion' | 'value' }
  perceived_bias?: string
}

export type LLMDecisionResult = {
  action: {
    type: string        // Free-form action description generated by LLM
    target?: string     // Target agent seed
    intensity: number   // 0-1
  }
  reasoning: string
  inner_monologue: string
  dialogue?: string
  behavior_description: string
  new_location?: string  // Location after action
  effects: {
    energy_delta: number
    stress_delta: number
    focus_delta: number
    emotion: string
    emotion_intensity: number
    relationship_delta?: number
    is_conflict: boolean
    goal_progress?: string
  }
  system_feedback?: SystemFeedback
}

/**
 * Build the full context prompt for an agent
 * Information fog of war + spatial awareness + system output injection
 */
function buildAgentPrompt(agent: PersonalAgentState, world: WorldSlice): string {
  const knowledge = extractWorldKnowledge(world)

  // === Location system ===
  const myLocation = agent.location || 'unknown'

  // People at the same location
  const colocated: PersonalAgentState[] = []
  // People at different locations
  const elsewhere: PersonalAgentState[] = []

  for (const other of world.agents.npcs) {
    if (other.genetics.seed === agent.genetics.seed) continue
    if (other.life_status !== 'alive') continue
    if (agent.location && other.location && other.location === agent.location) {
      colocated.push(other)
    } else {
      elsewhere.push(other)
    }
  }

  // === Information visibility: filter by social relationships ===
  const closeAllies: PersonalAgentState[] = []
  const acquaintances: PersonalAgentState[] = []
  const enemies: PersonalAgentState[] = []
  const strangers: PersonalAgentState[] = []

  for (const other of world.agents.npcs) {
    if (other.genetics.seed === agent.genetics.seed) continue
    if (other.life_status !== 'alive') continue
    const rel = agent.relations[other.genetics.seed]
    if (rel == null) {
      strangers.push(other)
    } else if (rel > 0.3) {
      closeAllies.push(other)
    } else if (rel < -0.3) {
      enemies.push(other)
    } else {
      acquaintances.push(other)
    }
  }

  // Build agent info based on relationship depth
  const buildAgentInfo = (a: PersonalAgentState, detail: 'full' | 'partial' | 'vague') => {
    const rel = agent.relations[a.genetics.seed]
    const relLabel = rel != null
      ? rel > 0.5 ? 'close' : rel > 0 ? 'friendly' : rel > -0.5 ? 'cold' : 'hostile'
      : 'stranger'
    const occLabel = a.occupation ? ` (${a.occupation})` : ''
    const locLabel = a.location ? ` [at ${a.location}]` : ''
    const isHere = colocated.includes(a) ? ' <-- RIGHT HERE' : ''

    // Pull relationship backstory from agent's memory
    const relMemory = agent.memory_short
      .filter(m => m.content.includes(a.identity.name) || m.id.includes(a.genetics.seed))
      .slice(-1)[0]
    const relStory = relMemory ? `\n    History: ${relMemory.content.substring(0, 100)}` : ''

    // Shared/conflicting goals
    const sharedGoals = agent.goals.filter(g =>
      a.goals.some(ag => g.includes(a.identity.name) || ag.includes(agent.identity.name) ||
        g.split(/\s+/).filter(w => w.length > 2).some(w => ag.includes(w)))
    )
    const goalOverlap = sharedGoals.length > 0
      ? `\n    Shared interest: ${sharedGoals[0].substring(0, 60)}`
      : ''

    if (detail === 'full') {
      const lastAction = a.last_action_description
        ? `\n    Just did: ${a.last_action_description.substring(0, 100)}`
        : ''
      const emotionLabel = a.emotion.label !== 'neutral' ? `\n    Looks: ${a.emotion.label}` : ''
      const dialogue = a.last_dialogue ? `\n    Said: "${a.last_dialogue.substring(0, 60)}"` : ''
      return `- ${a.identity.name}${occLabel} [seed:${a.genetics.seed}]: ${relLabel}(${rel?.toFixed(1)})${locLabel}${isHere}${emotionLabel}${lastAction}${dialogue}${relStory}${goalOverlap}`
    } else if (detail === 'partial') {
      const lastAction = a.last_action_description
        ? `\n    Seems: ${a.last_action_description.substring(0, 50)}...`
        : ''
      return `- ${a.identity.name}${occLabel} [seed:${a.genetics.seed}]: ${relLabel}${rel != null ? `(${rel.toFixed(1)})` : ''}${locLabel}${isHere}${lastAction}${relStory}${goalOverlap}`
    } else {
      return `- ${a.identity.name}${occLabel}: ${relLabel}${locLabel}`
    }
  }

  const knownPeople = [
    ...closeAllies.map(a => buildAgentInfo(a, 'full')),
    ...acquaintances.map(a => buildAgentInfo(a, 'partial')),
    ...enemies.map(a => buildAgentInfo(a, 'partial')),
    ...strangers.slice(0, 5).map(a => buildAgentInfo(a, 'vague')),
  ].join('\n')

  // Event visibility
  const knownSeeds = new Set([
    agent.genetics.seed,
    ...closeAllies.map(a => a.genetics.seed),
    ...acquaintances.map(a => a.genetics.seed),
    ...enemies.map(a => a.genetics.seed),
  ])

  const recentEvents = world.events
    .slice(-30)
    .filter(e => e.type !== 'tick')
    .filter(e => {
      if (e.id.includes(agent.genetics.seed)) return true
      for (const seed of knownSeeds) {
        if (e.id.includes(seed)) return true
      }
      if (['world_created', 'world_initialized', 'agent_death', 'agent_reincarnation', 'agent_spawn'].includes(e.type)) return true
      return false
    })
    .slice(-8)
    .map(e => {
      const payload = e.payload as Record<string, unknown> | undefined
      if (payload?.summary) return `- ${payload.summary}`
      switch (e.type) {
        case 'world_created':
          return `- World born: ${payload?.narrative_seed || 'A new world begins'}`
        case 'world_initialized':
          return `- ${(payload?.agent_names as string[])?.join(', ') || 'People'} arrived in this world`
        case 'agent_death':
          return `- ${payload?.agent_name || 'Someone'} died (${payload?.cause || 'unknown cause'})`
        case 'agent_spawn':
          return `- ${payload?.agent_name || 'A newcomer'} appeared`
        default:
          return null
      }
    })
    .filter(Boolean)
    .join('\n')

  // Rumors
  const rumors = world.events
    .slice(-20)
    .filter(e => e.type === 'micro' && !e.id.includes(agent.genetics.seed))
    .filter(e => {
      for (const seed of knownSeeds) {
        if (e.id.includes(seed)) return false
      }
      return true
    })
    .slice(-3)
    .map(e => {
      const payload = e.payload as Record<string, unknown> | undefined
      const summary = (payload?.summary as string) || ''
      return summary ? `- Heard someone ${summary.substring(0, 20)}... (rumor)` : null
    })
    .filter(Boolean)
    .join('\n')

  // Recent memories
  const recentMemories = [...agent.memory_short]
    .slice(-5)
    .map(m => `- ${m.content}`)
    .join('\n')

  // Active narratives
  const activeNarratives = world.narratives.patterns
    .filter(p => p.participants.includes(agent.genetics.seed) && (p.status === 'developing' || p.status === 'climax'))
    .map(p => {
      const names = world.agents.npcs
        .filter(a => p.participants.includes(a.genetics.seed))
        .map(a => a.identity.name)
      return `- ${p.type}: ${names.join(' & ')} (${p.status === 'climax' ? 'climax' : 'developing'}, intensity ${p.intensity.toFixed(1)})`
    })
    .join('\n')

  // === System pressure injection — make mechanisms felt ===
  const pressures: string[] = []

  // Reputation pressure — who's above you, who's threatening your position
  if (world.systems?.reputation) {
    const allReps = (world.systems.reputation as any).reputations as Record<string, any> | undefined
    const myRep = allReps?.[agent.genetics.seed]

    if (myRep && allReps) {
      // Find who's above and below you
      const entries = Object.entries(allReps)
      const sorted = entries.sort((a, b) => (b[1].influence || 0) - (a[1].influence || 0))
      const myRank = sorted.findIndex(([id]) => id === agent.genetics.seed)

      if (myRank >= 0) {
        const above = myRank > 0 ? sorted[myRank - 1] : null
        const below = myRank < sorted.length - 1 ? sorted[myRank + 1] : null

        const aboveName = above ? world.agents.npcs.find(a => a.genetics.seed === above[0])?.identity.name : null
        const belowName = below ? world.agents.npcs.find(a => a.genetics.seed === below[0])?.identity.name : null

        if (myRank <= 2 && sorted.length > 3) {
          pressures.push(`You are one of the most influential people here (rank ${myRank + 1}). Others look to you for direction.`)
        } else if (myRank >= sorted.length - 2 && sorted.length > 3) {
          pressures.push(`You have little influence here (rank ${myRank + 1} of ${sorted.length}). ${aboveName ? `${aboveName} holds the power you lack.` : ''}`)
        }

        if (belowName && below && Math.abs((below[1].influence || 0) - (myRep.influence || 0)) < 0.1) {
          pressures.push(`${belowName} is catching up to your influence — your position is not secure.`)
        }
      }

      // Reputation damage
      if (myRep.trustworthiness < 0.35) {
        pressures.push(`People don't trust you. Your promises carry little weight.`)
      }
      if (myRep.benevolence < 0.3) {
        pressures.push(`You are seen as selfish. Few will help you when you need it.`)
      }

      // Recent reputation events
      const history = (myRep.history as Array<{ tick: number; action_type: string; impact: Record<string, number>; description: string }>) || []
      const recentEvent = history.slice(-1)[0]
      if (recentEvent?.description) {
        pressures.push(`Recent: ${recentEvent.description}`)
      }
    }
  }

  // Resource pressure — concrete scarcity, not abstract
  if (world.systems?.resources) {
    const resources = (world.systems.resources as any).resources as Record<string, any> | undefined
    if (resources) {
      for (const [, res] of Object.entries(resources)) {
        const ratio = (res.amount || 0) / Math.max(1, res.max_amount || 100)
        if (ratio < 0.3 && res.name) {
          const daysLeft = Math.max(1, Math.floor(res.amount / Math.max(1, res.regeneration_rate || 1)))
          pressures.push(`${res.name} is running dangerously low (${Math.floor(ratio * 100)}% remaining, ~${daysLeft} cycles before depletion). Competition for it will intensify.`)
        }
      }
    }
  }

  // Tension pressure — specific, involving named agents
  if (world.systems?.tension) {
    const tensions = (world.systems.tension as any).tensions as Record<string, any> | undefined
    if (tensions) {
      for (const [, t] of Object.entries(tensions)) {
        if ((t.status === 'building' || t.status === 'peak') && Array.isArray(t.target_agents) && t.target_agents.includes(agent.genetics.seed)) {
          const otherIds = (t.target_agents as string[]).filter((id: string) => id !== agent.genetics.seed)
          const otherNames = otherIds
            .map((id: string) => world.agents.npcs.find(a => a.genetics.seed === id)?.identity.name)
            .filter(Boolean)
          const level = t.level as number || 0
          if (level > 0.7) {
            pressures.push(`A crisis is reaching its peak${otherNames.length > 0 ? ` involving you and ${otherNames.join(', ')}` : ''}: ${t.source || 'things cannot continue like this'}.`)
          } else if (level > 0.4) {
            pressures.push(`Tension is building${otherNames.length > 0 ? ` between you and ${otherNames.join(', ')}` : ''}: ${t.source || 'something has to give'}.`)
          }
        }
      }
    }
  }

  // Social role pressure — expectations and conflicts
  if (world.systems?.social_roles) {
    const roles = (world.systems.social_roles as any).agentRoles?.[agent.genetics.seed] as Array<{ name: string; expectations: string[]; obligations: string[] }> | undefined
    if (roles && roles.length > 0) {
      const primaryRole = roles[0]
      if (primaryRole.obligations?.length > 0) {
        pressures.push(`As ${primaryRole.name}, you are expected to: ${primaryRole.obligations.slice(0, 2).join('; ')}.`)
      }
    }
    const conflicts = (world.systems.social_roles as any).roleConflicts as Array<{ agent_id: string; conflict_description: string }> | undefined
    if (conflicts) {
      const myConflicts = conflicts.filter((c: any) => c.agent_id === agent.genetics.seed)
      for (const c of myConflicts.slice(0, 1)) {
        pressures.push(`You feel torn: ${c.conflict_description}`)
      }
    }
  }

  // Agent vitals pressure — body speaks
  if (agent.vitals.energy < 0.25) {
    pressures.push(`You are exhausted. Your body demands rest or sustenance.`)
  }
  if (agent.vitals.stress > 0.7) {
    pressures.push(`You are highly stressed. The pressure is becoming unbearable.`)
  }

  const pressureSection = pressures.length > 0
    ? `\n## Pressures bearing down on you\n${pressures.map(p => `- ${p}`).join('\n')}`
    : ''

  // Meme whispers — ideas that have spread to this agent
  let whispersSection = ''
  if (world.systems?.memes) {
    const memeData = (world.systems.memes as any).memes
    if (memeData) {
      const agentMemes = Object.values(memeData)
        .filter((m: any) => Array.isArray(m.carriers) && m.carriers.includes(agent.genetics.seed))
        .slice(0, 4)
        .map((m: any) => m.content)
      if (agentMemes.length > 0) {
        whispersSection = `\n## Whispers (ideas you've been hearing)\n${agentMemes.map((c: string) => `- "${c}"`).join('\n')}`
      }
    }
  }

  // Role models — successful agents this agent admires (social learning)
  let roleModelsSection = ''
  if (world.systems?.reputation) {
    const allReps = (world.systems.reputation as any).reputations as Record<string, any> | undefined
    if (allReps) {
      const myRelations = agent.relations || {}
      const admired = Object.entries(allReps)
        .filter(([id, rep]) => id !== agent.genetics.seed && (rep.influence > 0.5 || rep.competence > 0.6) && (myRelations[id] || 0) > 0)
        .sort((a, b) => (b[1].influence || 0) - (a[1].influence || 0))
        .slice(0, 2)

      if (admired.length > 0) {
        const modelDescriptions = admired.map(([id, rep]) => {
          const modelAgent = world.agents.npcs.find(a => a.genetics.seed === id)
          const name = modelAgent?.identity.name || id
          return `- ${name} (influence: ${(rep.influence as number).toFixed(1)}, competence: ${(rep.competence as number).toFixed(1)})`
        })
        roleModelsSection = `\n## Role models (people you look up to)\n${modelDescriptions.join('\n')}`
      }
    }
  }

  const systemSection = '' // replaced by pressureSection

  // Colocated people — build a rich scene description
  const colocatedNames = colocated.map(a => a.identity.name).join(', ')

  // Build scene: what's happening right here, right now
  const sceneLines: string[] = []
  for (const other of colocated) {
    const rel = agent.relations[other.genetics.seed]
    const relLabel = rel != null
      ? rel > 0.5 ? 'your ally' : rel > 0 ? 'friendly' : rel > -0.5 ? 'uneasy terms' : 'your rival'
      : 'a stranger'
    const doing = other.last_action_description
      ? other.last_action_description.substring(0, 80)
      : 'standing here'
    const saying = other.last_dialogue
      ? ` — said: "${other.last_dialogue.substring(0, 50)}"`
      : ''
    const mood = other.emotion.label !== 'neutral'
      ? ` (looks ${other.emotion.label})`
      : ''
    sceneLines.push(`- ${other.identity.name} (${relLabel}${mood}): ${doing}${saying}`)
  }
  const sceneSection = sceneLines.length > 0
    ? `\n## The scene right now (what you see)\n${sceneLines.join('\n')}`
    : ''

  const locationSection = `## Your current location
- Location: ${myLocation}
${colocated.length > 0 ? `- People here: ${colocatedNames}` : '- You are alone'}
${colocated.length > 0 ? `You can see and talk to these people right now.` : `No one is around.`}`

  // Detect world language for output instructions
  const worldLang = world.config?.language || 'en'
  const langInstruction = worldLang !== 'en'
    ? `\n\nIMPORTANT: All character-facing text (dialogue, behavior_description, inner_monologue, reasoning, action.type, effects.emotion, goal_progress) MUST be written in the same language as the world description (detected: ${worldLang}). The JSON keys themselves stay in English.`
    : ''

  return `You are "${agent.identity.name}". You are not an AI — you are this person.${langInstruction}

## What you want
${agent.goals.length > 0 ? agent.goals.map((g, i) => `${i + 1}. ${g}`).join('\n') : 'You have not decided what to do yet'}

## Where you are right now
${myLocation}${colocated.length > 0 ? ` — here with you: ${colocatedNames}` : ' — alone'}
${sceneSection}
${pressureSection}

## Who you are
${agent.occupation || 'no occupation'} | ${agent.voice || 'ordinary voice'} | ${agent.approach || 'ordinary approach'}
Core belief: ${agent.core_belief || 'none'}
${agent.expertise?.length ? `Expertise: ${agent.expertise.join(', ')}` : ''}
Energy: ${(agent.vitals.energy * 100).toFixed(0)}% | Stress: ${(agent.vitals.stress * 100).toFixed(0)}% | Emotion: ${agent.emotion.label}
${agent.last_action_description ? `Just did: ${agent.last_action_description}` : ''}
${agent.last_dialogue ? `Just said: "${agent.last_dialogue}"` : ''}

## People you know
${knownPeople || 'You do not know anyone'}

## What you remember
${recentMemories || 'Your mind is blank'}

## The world
${knowledge.environment.description}
${knowledge.social.pressures.length > 0 ? `Pressures: ${knowledge.social.pressures.join('; ')}` : ''}

${recentEvents ? `## Recent events\n${recentEvents}` : ''}
${rumors ? `## Rumors\n${rumors}` : ''}
${activeNarratives ? `## Ongoing stories\n${activeNarratives}` : ''}
${whispersSection}${roleModelsSection}

---

Now, as "${agent.identity.name}", decide what to do next. Be yourself. Act on your desires, fears, grudges, and ambitions.

You are at "${myLocation}"${colocated.length > 0 ? ` with ${colocatedNames}` : ' alone'}. You can only interact face-to-face with people at the same location.

Return strict JSON:
{
  "action": {
    "type": "what you are doing (free description)",
    "target": "if involving someone, their seed; otherwise omit",
    "intensity": 0.0 to 1.0
  },
  "reasoning": "third person, why this decision (1-2 sentences)",
  "inner_monologue": "first person inner thoughts",
  "dialogue": "what you say out loud (omit if silent)",
  "behavior_description": "what happened, described in third person",
  "new_location": "where you are after the action (if you didn't move, use current location)",
  "effects": {
    "energy_delta": -0.1 to 0.1,
    "stress_delta": -0.1 to 0.1,
    "focus_delta": -0.1 to 0.1,
    "emotion": "emotion after the action",
    "emotion_intensity": 0.0 to 1.0,
    "relationship_delta": relationship change (-0.3 to 0.3),
    "is_conflict": true/false,
    "goal_progress": "which goal was advanced (optional)"
  },
  "system_feedback": {
    "reputation_impact": [{"dimension": "trustworthiness|competence|benevolence|status|influence", "delta": -0.1 to 0.1, "reason": "why"}],
    "current_role": "your perceived social role right now (e.g. leader, mediator, follower, guardian, innovator, outsider)",
    "role_conflict": "if you feel torn between two roles, describe it briefly",
    "resource_action": {"resource": "what resource", "strategy": "direct_compete|cooperate|share|hoard|steal|deceive", "amount_hint": 1-10},
    "tension_effect": "building|releasing|neutral",
    "meme_spread": {"content": "an idea/belief/behavior you are spreading", "category": "belief|behavior|knowledge|emotion|value"},
    "perceived_bias": "name of cognitive bias you suspect affected this decision (optional)"
  }
}

All fields in system_feedback are optional — include only what applies to this action.

Return only JSON, nothing else.`
}

/**
 * Parse LLM JSON response
 */
function parseLLMResponse(responseText: string): LLMDecisionResult | null {
  try {
    const jsonMatch = responseText.match(/\{[\s\S]*\}/)
    if (!jsonMatch) return null

    const parsed = JSON.parse(jsonMatch[0])

    if (!parsed.behavior_description) return null

    const effects = parsed.effects || {}

    return {
      action: {
        type: parsed.action?.type || 'action',
        target: parsed.action?.target || undefined,
        intensity: Math.max(0, Math.min(1, Number(parsed.action?.intensity) || 0.5)),
      },
      reasoning: parsed.reasoning || '',
      inner_monologue: parsed.inner_monologue || '',
      dialogue: parsed.dialogue || undefined,
      behavior_description: parsed.behavior_description,
      new_location: parsed.new_location || undefined,
      effects: {
        energy_delta: clamp(Number(effects.energy_delta) || 0, -0.3, 0.3),
        stress_delta: clamp(Number(effects.stress_delta) || 0, -0.3, 0.3),
        focus_delta: clamp(Number(effects.focus_delta) || 0, -0.3, 0.3),
        emotion: effects.emotion || 'calm',
        emotion_intensity: Math.max(0, Math.min(1, Number(effects.emotion_intensity) || 0.3)),
        relationship_delta: effects.relationship_delta != null
          ? clamp(Number(effects.relationship_delta), -0.5, 0.5)
          : undefined,
        is_conflict: Boolean(effects.is_conflict),
        goal_progress: effects.goal_progress || undefined,
      },
      system_feedback: parseSystemFeedback(parsed.system_feedback),
    }
  } catch {
    return null
  }
}

function parseSystemFeedback(raw: unknown): SystemFeedback | undefined {
  if (!raw || typeof raw !== 'object') return undefined

  const fb = raw as Record<string, unknown>
  const result: SystemFeedback = {}
  let hasAny = false

  if (Array.isArray(fb.reputation_impact)) {
    const valid = fb.reputation_impact
      .filter((r: unknown) => r && typeof r === 'object' && (r as Record<string, unknown>).dimension)
      .map((r: Record<string, unknown>) => ({
        dimension: String(r.dimension),
        delta: clamp(Number(r.delta) || 0, -0.15, 0.15),
        reason: String(r.reason || ''),
      }))
    if (valid.length > 0) { result.reputation_impact = valid; hasAny = true }
  }

  if (typeof fb.current_role === 'string' && fb.current_role) {
    result.current_role = fb.current_role; hasAny = true
  }
  if (typeof fb.role_conflict === 'string' && fb.role_conflict) {
    result.role_conflict = fb.role_conflict; hasAny = true
  }

  if (fb.resource_action && typeof fb.resource_action === 'object') {
    const ra = fb.resource_action as Record<string, unknown>
    const validStrategies = ['direct_compete', 'cooperate', 'share', 'hoard', 'steal', 'deceive'] as const
    const strategy = validStrategies.find(s => s === ra.strategy)
    if (ra.resource && strategy) {
      result.resource_action = {
        resource: String(ra.resource),
        strategy,
        amount_hint: clamp(Number(ra.amount_hint) || 1, 0, 20),
      }
      hasAny = true
    }
  }

  if (fb.tension_effect === 'building' || fb.tension_effect === 'releasing' || fb.tension_effect === 'neutral') {
    result.tension_effect = fb.tension_effect; hasAny = true
  }

  if (fb.meme_spread && typeof fb.meme_spread === 'object') {
    const ms = fb.meme_spread as Record<string, unknown>
    const validCategories = ['belief', 'behavior', 'knowledge', 'emotion', 'value'] as const
    const category = validCategories.find(c => c === ms.category)
    if (ms.content && category) {
      result.meme_spread = { content: String(ms.content), category }
      hasAny = true
    }
  }

  if (typeof fb.perceived_bias === 'string' && fb.perceived_bias) {
    result.perceived_bias = fb.perceived_bias; hasAny = true
  }

  return hasAny ? result : undefined
}

function clamp(v: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, v))
}

/**
 * Generate agent decision via LLM
 * thisTickContext: events that already happened this tick at the same location (injected during wave execution)
 */
export async function generateAgentDecisionViaLLM(
  agent: PersonalAgentState,
  world: WorldSlice,
  thisTickContext?: string
): Promise<LLMDecisionResult> {
  const client = createAnthropicClient()
  const model = getModel()
  let prompt = buildAgentPrompt(agent, world)

  // Inject real-time context for this tick (what colocated agents just did)
  if (thisTickContext) {
    prompt = prompt.replace(
      '---\n\nNow, as',
      `## What is happening right now (you are witnessing this)\n${thisTickContext}\n\n**You must react to this.** If someone speaks to you, respond; if someone does something that affects you, deal with it. Do not ignore what is happening before your eyes.\n\n---\n\nNow, as`
    )
  }

  const responseText = await streamText(client, {
    model,
    max_tokens: 2048,
    messages: [{ role: 'user', content: prompt }],
  })

  if (!responseText) {
    throw new Error('LLM returned empty response')
  }

  const result = parseLLMResponse(responseText)
  if (!result) {
    throw new Error('Failed to parse LLM decision: ' + responseText.substring(0, 200))
  }

  return result
}
