import type { PersonalAgentState } from '@/domain/world'
import { createPersonalAgent } from '@/domain/agents'
import { createAnthropicClient, getModel, streamText } from './anthropic'

type GenerateAgentsOptions = {
  prompt: string
  count: number
}

type AgentSpec = {
  seed: string
  name: string
  persona: {
    openness: number
    stability: number
    attachment: number
    agency: number
    empathy: number
  }
  vitals: {
    energy: number
    stress: number
    sleep_debt: number
    focus: number
    aging_index: number
  }
  backstory?: string
  goals?: string[]

  // Personality fields - dynamically generated by LLM based on world context
  occupation?: string
  voice?: string
  approach?: string
  expertise?: string[]
  core_belief?: string
  location?: string
}

// Initial relationships between NPCs
type RelationSpec = {
  from: string  // seed
  to: string    // seed
  value: number // -1 to 1
  label: string // relationship description
}

// Complete generation result from LLM
type GenerationResult = {
  agents: AgentSpec[]
  relations: RelationSpec[]
}

export async function generatePersonalAgents(
  options: GenerateAgentsOptions
): Promise<PersonalAgentState[]> {
  const { prompt, count } = options

  // Split into batches of 5 to avoid API timeouts on large requests
  const BATCH_SIZE = 5
  const allAgents: PersonalAgentState[] = []
  const allRelationSpecs: RelationSpec[] = []

  const totalBatches = Math.ceil(count / BATCH_SIZE)

  for (let batch = 0; batch < totalBatches; batch++) {
    const batchCount = Math.min(BATCH_SIZE, count - batch * BATCH_SIZE)
    const existingNames = allAgents.map(a => `${a.identity.name} (${a.occupation || 'unknown'}, seed: ${a.genetics.seed})`).join(', ')

    console.log(`Agent generator: batch ${batch + 1}/${totalBatches}, generating ${batchCount} agents...`)

    const { specs, relationSpecs } = await generateAgentBatch(prompt, batchCount, existingNames)

    // Convert specs to PersonalAgentState
    const agents = specs.map((spec) => {
      const agent = createPersonalAgent(spec.seed)
      return {
        ...agent,
        identity: { name: spec.name || spec.seed },
        persona: spec.persona,
        vitals: spec.vitals,
        goals: spec.goals || [],
        occupation: spec.occupation,
        voice: spec.voice,
        approach: spec.approach,
        expertise: spec.expertise,
        core_belief: spec.core_belief,
        location: spec.location || 'unknown',
        success_metrics: {
          wealth: 0,
          reputation: 0,
          power: 0,
          knowledge: 0,
        },
      }
    })

    allAgents.push(...agents)
    allRelationSpecs.push(...relationSpecs)
  }

  // Write relationships into each NPC's relations field (across all batches)
  for (const rel of allRelationSpecs) {
    const fromAgent = allAgents.find(a => a.genetics.seed === rel.from)
    if (fromAgent) {
      fromAgent.relations[rel.to] = Math.max(-1, Math.min(1, rel.value))
      const toAgent = allAgents.find(a => a.genetics.seed === rel.to)
      if (toAgent) {
        fromAgent.memory_short.push({
          id: `init-rel-${rel.from}-${rel.to}`,
          content: `Relationship with ${toAgent.identity.name}: ${rel.label}`,
          importance: 0.7,
          emotional_weight: Math.abs(rel.value) * 0.5,
          source: 'self' as const,
          timestamp: new Date().toISOString(),
          decay_rate: 0.02,
          retrieval_strength: 0.9,
        })
      }
    }
  }

  return allAgents
}

/**
 * Generate a single batch of agents via LLM
 */
async function generateAgentBatch(
  worldContext: string,
  count: number,
  existingAgents: string
): Promise<{ specs: AgentSpec[]; relationSpecs: RelationSpec[] }> {
  const client = createAnthropicClient()
  const model = getModel()

  const existingSection = existingAgents
    ? `\n\n**Already created characters:** ${existingAgents}\nNew characters MUST have relationships with at least 1 existing character. Use their seeds in the relations array.`
    : ''

  const systemPrompt = `You are a character creator for a world simulation. Based on the world context below, generate ${count} unique agents and establish their social relationship network.

World context: ${worldContext}${existingSection}

For each agent, provide:
1. seed: unique identifier (kebab-case, descriptive, for internal system use)
2. name: a name that fits the world's setting and language
3. persona: personality traits (openness, stability, attachment, agency, empathy) values 0-1
4. vitals: life state (energy, stress, sleep_debt, focus, aging_index) values 0-1
5. backstory: brief background story (must intersect with other characters, not isolated)
6. goals: 2-3 specific, actionable goals (at least one involving another character)

**Important - personality fields:**
7. occupation: a role/profession that fits the world setting (be creative and specific)
8. voice: speaking style (brief description)
9. approach: how they handle things (brief description)
10. expertise: 3-5 specific skills relevant to the world
11. core_belief: one sentence - the core value driving this character's behavior
12. location: initial location (use only 2-3 distinct locations for ALL characters — most people should be near others so interactions happen immediately)

**Relationship network requirements (critical):**
- Each character must have relationships with at least 2 others
- Diverse relationship types: allies, rivals, mentor-student, family, secret admirers, debts, grudges, etc.
- Relationship values range from -1 (mortal enemies) to 1 (closest bond), 0 is neutral
- Relationships must be bidirectional but not necessarily symmetric (A likes B doesn't mean B likes A)

**Language requirement:**
- Generate ALL content in the SAME language as the world context above

Return a JSON object:
{
  "agents": [
    {
      "seed": "example-agent",
      "name": "...",
      "persona": { "openness": 0.7, "stability": 0.6, "attachment": 0.4, "agency": 0.8, "empathy": 0.3 },
      "vitals": { "energy": 0.8, "stress": 0.3, "sleep_debt": 0.1, "focus": 0.7, "aging_index": 0.2 },
      "backstory": "...",
      "goals": ["goal 1", "goal 2", "goal 3"],
      "occupation": "...",
      "voice": "...",
      "approach": "...",
      "expertise": ["skill1", "skill2", "skill3"],
      "core_belief": "...",
      "location": "..."
    }
  ],
  "relations": [
    { "from": "agent-a", "to": "agent-b", "value": -0.4, "label": "reason" },
    { "from": "agent-b", "to": "agent-a", "value": 0.3, "label": "reason" }
  ]
}`

  const responseText = await streamText(client, {
    model,
    max_tokens: 8192,
    messages: [
      {
        role: 'user',
        content: systemPrompt,
      },
    ],
  })

  if (!responseText) {
    throw new Error('No text content in response')
  }

  // Extract JSON from response
  const jsonMatch = responseText.match(/\{[\s\S]*\}/)
  if (!jsonMatch) {
    throw new Error('Failed to parse agent specifications from response')
  }

  const parsed = JSON.parse(jsonMatch[0])

  let specs: AgentSpec[]
  let relationSpecs: RelationSpec[] = []

  if (Array.isArray(parsed)) {
    specs = parsed
  } else {
    specs = parsed.agents || []
    relationSpecs = parsed.relations || []
  }

  return { specs, relationSpecs }
}
