import type { NarrativeSystem } from './narrative'
import type { Reputation, ReputationDimension } from '@/engine/reputation-system'
import type { SocialRole, RoleConflict } from '@/engine/social-role-system'
import type { Resource, ResourceClaim } from '@/engine/resource-competition-system'
import type { DramaticTension, TensionEvent } from '@/engine/dramatic-tension-system'
import type { EmergentProperty } from '@/engine/emergent-property-detector'
import type { Meme, MemeTransmission } from '@/engine/meme-propagation-system'
import type { AttentionState } from '@/engine/attention-mechanism'
import type { KnowledgeNode, KnowledgeEdge } from '@/engine/knowledge-graph'

export type AgentKind = 'world' | 'persona' | 'personal' | 'social'

export type MemoryRecord = {
  id: string
  content: string
  importance: number
  emotional_weight: number
  source: 'self' | 'social' | 'world'
  timestamp: string
  decay_rate: number
  retrieval_strength: number
}

export type VitalsState = {
  energy: number
  stress: number
  sleep_debt: number
  focus: number
  aging_index: number
}

export type PersonaState = {
  openness: number
  stability: number
  attachment: number
  agency: number
  empathy: number
}

export type SocialContext = {
  macro_events: string[]
  narratives: string[]
  pressures: string[]
  institutions: string[]
  ambient_noise: string[]
}

export type PersonalAgentState = {
  kind: 'personal'
  genetics: {
    seed: string
  }
  identity: {
    name: string
  }
  memory_short: MemoryRecord[]
  memory_long: MemoryRecord[]
  vitals: VitalsState
  emotion: {
    label: string
    intensity: number
  }
  persona: PersonaState
  goals: string[]
  relations: Record<string, number>
  action_history: Array<{ type: string; timestamp: string }>
  
  // Life cycle
  life_status: 'alive' | 'dying' | 'dead' | 'reincarnating'
  death_tick?: number
  cause_of_death?: string
  legacy?: string[]

  // Agent personality - dynamically generated by LLM based on world context
  occupation?: string
  voice?: string
  approach?: string
  expertise?: string[]
  core_belief?: string
  success_metrics?: Record<string, number>

  // Time engine - activity patterns
  activity_pattern?: number[]  // 24 维，每小时的活跃概率 [0-1]
  timezone_offset?: number  // 时区偏移（小时）
  sleep_schedule?: {
    typical_sleep_hour: number  // 通常睡觉时间（0-23）
    typical_wake_hour: number   // 通常起床时间（0-23）
  }
  
  // Emergent narrative - dynamic role identification
  narrative_roles?: {
    [narrativeId: string]: {
      role: 'protagonist' | 'antagonist' | 'supporting' | 'observer' | 'catalyst'
      involvement: number  // 参与度 [0-1]
      impact: number       // 影响力 [0-1]
    }
  }

  // LLM Agent decision output - updated each tick
  last_action_description?: string
  last_dialogue?: string
  last_inner_monologue?: string
  location?: string
}

// ===== System snapshot types =====

export type ReputationSnapshot = {
  reputations: Record<string, Reputation>
  socialNetwork: Record<string, string[]>
}

export type SocialRoleSnapshot = {
  agentRoles: Record<string, SocialRole[]>
  roleConflicts: RoleConflict[]
}

export type ResourceSnapshot = {
  resources: Record<string, Resource>
}

export type TensionSnapshot = {
  tensions: Record<string, DramaticTension>
  events: TensionEvent[]
  tensionCounter: number
}

export type EmergenceSnapshot = {
  detectedProperties: Array<Omit<EmergentProperty, 'indicators'> & { indicators: Record<string, number> }>
  propertyCounter: number
}

export type MemeSnapshot = {
  memes: Record<string, Meme>
  transmissions: MemeTransmission[]
  memeCounter: number
}

export type AttentionSnapshot = {
  states: Record<string, Omit<AttentionState, 'attention_weights'> & { attention_weights: Record<string, number> }>
}

export type KnowledgeGraphSnapshot = {
  nodes: KnowledgeNode[]
  edges: KnowledgeEdge[]
}

export type SystemsState = {
  reputation?: ReputationSnapshot
  social_roles?: SocialRoleSnapshot
  resources?: ResourceSnapshot
  tension?: TensionSnapshot
  emergence?: EmergenceSnapshot
  memes?: MemeSnapshot
  attention?: AttentionSnapshot
  knowledge_graph?: KnowledgeGraphSnapshot
}

export type WorldConfig = {
  /** Language for LLM prompts and generated content (e.g. 'zh', 'en', 'ja') */
  language: string
  /** Reincarnation name suffix (e.g. '·Reborn', '·转世') */
  reborn_suffix?: string
  /** Past life memory prefix (e.g. 'Past life memory:', '前世记忆：') */
  past_life_prefix?: string
}

export type WorldSlice = {
  world_id: string
  tick: number
  time: string
  config: WorldConfig
  environment: {
    description: string
  }
  social_context: SocialContext
  agents: {
    director: { kind: 'world'; id: string }
    creator: { kind: 'persona'; id: string }
    personal: PersonalAgentState
    social: { kind: 'social'; id: string }
    npcs: PersonalAgentState[]
  }
  narratives: NarrativeSystem
  events: Array<{ id: string; type: string; timestamp: string; payload?: Record<string, unknown> }>
  relations: Record<string, number>
  active_hooks: string[]
  systems: SystemsState
  tick_summary?: string
}

export function createInitialWorldSlice(): WorldSlice {
  return {
    world_id: 'world-1',
    tick: 0,
    time: new Date(0).toISOString(),
    config: {
      language: 'zh',
    },
    environment: { description: 'calm' },
    social_context: {
      macro_events: [],
      narratives: [],
      pressures: [],
      institutions: [],
      ambient_noise: [],
    },
    agents: {
      director: { kind: 'world', id: 'director-1' },
      creator: { kind: 'persona', id: 'creator-1' },
      personal: {
        kind: 'personal',
        life_status: 'alive',
        genetics: { seed: 'default-user' },
        identity: { name: 'user' },
        memory_short: [],
        memory_long: [],
        vitals: {
          energy: 0.7,
          stress: 0.2,
          sleep_debt: 0.1,
          focus: 0.6,
          aging_index: 0.1,
        },
        emotion: { label: 'neutral', intensity: 0.2 },
        persona: {
          openness: 0.5,
          stability: 0.5,
          attachment: 0.5,
          agency: 0.5,
          empathy: 0.5,
        },
        goals: [],
        relations: {},
        action_history: [],
      },
      social: { kind: 'social', id: 'social-1' },
      npcs: [],
    },
    narratives: {
      patterns: [],
      arcs: [],
      summaries: [],
      stats: {
        total_patterns: 0,
        active_patterns: 0,
        concluded_patterns: 0,
        total_arcs: 0,
        completed_arcs: 0
      }
    },
    events: [],
    relations: {},
    active_hooks: [],
    systems: {},
  }
}
